BeginVegan/BV-Frontend

- src/components/Layout/ControllBar.jsx
- src/components/Layout/Header.jsx
- src/components/Layout/MypageLayout.jsx
- src/components/Layout/Sidebar.jsx
> route 주소 상수화 적용

- src/components/store/BestStoreCard.jsx
- src/components/store/StoreCard.jsx
- src/pages/Best/BestPage.jsx
- src/pages/Error/NotFoundPage.jsx
- src/pages/Main/MainPage.jsx
- src/routes/AppRoutes.jsx
- src/routes/ROUTES.js
- 리뷰, 예약, 평점 순으로 가게를 나열할 페이지 제작
- 임시 404페이지 제작
> bestPage 초안 제작

- src/components/search/SearchFilter.jsx
- src/components/store/VeganLevel.jsx
- 비건정도를 표현해주는 컴포넌트를 제작하여 따로 분리하였습니다
> VeganLevel 컴포넌트 제작

- src/pages/Restaurant/RestaurantDetailPage.jsx
- src/routes/AppRoutes.jsx
- src/routes/ROUTES.js
- 누락된 라우터 연결 작업 수행
- 리뷰 이미지 크기 고정
> 식당 상세페이지 라우터 연결

- package.json
- src/pages/Restaurant/RerservationRestaurant.jsx
- src/pages/Restaurant/RestaurantDetailPage.jsx
- src/routes/AppRoutes.jsx
- src/routes/ROUTES.js
- yarn.lock
- 식당 예약 페이지를 제작하였습니다.
- 날짜 입력을 위한 datepicker 패키지를 설치하였습니다.
> 식당 예약페이지 초안 제작

- src/pages/Admin/Register/RegisterStepOne.jsx
- src/pages/Admin/Register/RegisterStepThree.jsx
- src/pages/Admin/Register/RegisterStepTwo.jsx
- src/pages/Admin/Register/RestaurantRegistration.jsx
- src/routes/AppRoutes.jsx
- src/routes/ROUTES.js
- 식당 등록 스텝별 페이지 제작
- STEP1
- ![localhost_5173_resturant_registration (3)](https://github.com/BeginVegan/BV-Frontend/assets/15073430/8a9b3b3c-55b9-4474-b1be-9cdccfdeb983)
- ![localhost_5173_resturant_registration (1)](https://github.com/BeginVegan/BV-Frontend/assets/15073430/07d01ede-1ca2-4543-b8e5-00917955bb3a)
- STEP3
- ![localhost_5173_resturant_registration (2)](https://github.com/BeginVegan/BV-Frontend/assets/15073430/9941791d-e103-4045-b8f1-c7d3463221ae)
> 식당 등록페이지 제작

- src/components/Layout/Footer.jsx
- src/components/Layout/MainLayout.jsx
- src/pages/Main/MainPage.jsx
> 푸터 고정 로직 변경으로 인한 코드 수정

- src/pages/Admin/Register/RegisterStepOne.jsx
- src/pages/Admin/Register/RegisterStepTwo.jsx
- src/pages/Admin/Register/RestaurantRegistration.jsx
- 식당 정보와 메뉴 정보가 함께 있는 등록페이지에서 식당 정보와 메뉴 정보를 분리하였습니다
> 식당 등록페이지 식당정보와 메뉴정보 분리

- src/api/apiConfig.js
axios 세팅변경 헤더나 디폴트 유알엘 적용해서 사용가능
용례 
``` const handleSessionTest = async () => {
const res = await Axios.get('member/session');
console.log(res);
};
기존
``` const handleSessionTest = async () => {
const res = await axios.get('fkel;afkla;fkle;afkae;lfek.겁나긴 백엔드 url/member/session');
console.log(res);
};
> refactor: :recycle: axios 설정 변경

- src/components/Layout/Sidebar.jsx
- src/pages/Personal/historyTabs/PurchaseHistory.jsx
- src/pages/Personal/historyTabs/ReservationHistory.jsx
- src/pages/Personal/historyTabs/ReviewHistory.jsx
- src/pages/Personal/historyTabs/VisitHistory.jsx
> refactor: :recycle: 마이페이지 전반적으로 반응형 추가

- index.html
- package.json
- src/pages/SearchResult/KakaoMap.jsx
- src/pages/SearchResult/SearchResultPage.jsx
- yarn.lock
> feat: :sparkles: 카카오지도 초안

- src/pages/Personal/historyTabs/ReservationHistory.jsx
> feat: :sparkles: feat/mypage/history/reservation

- src/components/restaurant/VeganLevel.jsx
- src/pages/Restaurant/RestaurantDetailPage.jsx
첫 프론트 작업입니다. 리뷰 시게 부탁드립니다.
추가 수정 필요 내역
1. 백엔드에서 S3 사진 요청 방식에 따라 식당 메인 이미지와 리뷰 이미지 등 수정 필요
2. 즐겨찾기 버튼 추가 작업 필요
3. 비건 레벨 태그 물어보기
4. 반응형으로 변경
+ 리팩토링
> restaurantDetailPage

- src/pages/Personal/BookmarkPage.jsx
- src/pages/Personal/DropPage.jsx
- src/pages/Personal/historyTabs/ReservationHistory.jsx
- src/pages/Personal/historyTabs/ReviewHistory.jsx
> feat: :sparkles: 예약 취소 / 회원 탈퇴 로직 추가

- src/pages/Personal/MyPageMain.jsx
- src/pages/Personal/SubmitReviewPage.jsx
- src/pages/Personal/historyTabs/ReservationHistory.jsx
- src/pages/Personal/historyTabs/ReviewHistory.jsx
- src/pages/Personal/historyTabs/VisitHistory.jsx
- src/pages/Personal/historyTabs/hooks/useRestaurantDetail.js
- src/routes/AppRoutes.jsx
리뷰 삭제시 바로 랜더링되게
리뷰성하면 마이페이지 메인으로 리다이렉션
방문관리에 리뷰안쓴거만 리뷰 버튼 생기게
> fix: :bug: 자잘한 버그 수정

- index.html
- package.json
- src/pages/Restaurant/BookmarkCheck.jsx
- src/pages/Restaurant/FormatTime12Hour.jsx
- src/pages/Restaurant/FormattedDateTime.jsx
- src/pages/Restaurant/Loading.jsx
- src/pages/Restaurant/ReservationMenu.jsx
- src/pages/Restaurant/RestaurantDetailPage.jsx
- src/pages/Restaurant/RestaurantImg.jsx
- src/pages/Restaurant/RestaurantMenu.jsx
- src/pages/Restaurant/RestaurntReview.jsx
- src/pages/Restaurant/StarRating.jsx
- yarn.lock
> 식당 상세페이지 이미지 띄어주기 수정

- src/pages/Personal/DropPage.jsx
- src/pages/Personal/MyPageMain.jsx
- src/pages/Personal/historyTabs/VisitHistory.jsx
마이페이지 리랜더
이미지 컨트롤러 이용 
회원탈퇴 Axios
포인트가 - 이면 왜 나무 ?
> fix: :bug: 수정 사항 반영

- src/api/apiConfig.js
- src/components/Layout/MypageLayout.jsx
- src/pages/Restaurant/BookButton.jsx
- src/pages/Restaurant/BookmarkCheck.jsx
- src/pages/Restaurant/RestaurantDetailPage.jsx
- src/pages/Restaurant/RestaurantImg.jsx
1. 식당 상세 페이지에서 식당 이미지를 프레임에 맞도록 수정
2. 예약하기 버튼 시 로그인 여부 판별 및 동작 분기 추가
3. 로그인 판별 여부 체크시 null인 경우도 판별 할 수 있도록 수정
> 1차 배포 후 버그 픽스

- src/components/Layout/ControllBar.jsx
- src/components/LoginAPIs/SocialGoogle.jsx
- src/components/LoginAPIs/SocialKakao.jsx
- src/pages/Loading/LoadingPage.jsx
- src/pages/Login/LoginPage.jsx
> fix: :bug: 프론트 #61 관련 수정사항

- src/components/Layout/ControllBar.jsx
- src/components/Layout/Hero.jsx
- src/components/Layout/MainHeader.jsx
- src/components/Layout/MainLayout.jsx
- src/components/common/Loading.jsx
- src/components/main/BestStoreCard.jsx
- src/hooks/useProgressiveImage.js
- src/pages/Admin/AdminPage.jsx
- src/pages/Admin/Register/RegisterManagement.jsx
- src/pages/Admin/Register/RestaurantRegistration.jsx
- src/pages/Admin/Reservation/ReservationManagementPage.jsx
- src/pages/Loading/LoadingPage.jsx
- src/pages/Main/MainPage.jsx
- src/routes/AppRoutes.jsx
- src/utils/atoms/isAuthenticatedAtom.js
- 메인 관리자 페이지 이동 버튼 url 수정 -> 수정 완료
- 헤더 로그인 버튼으로 바꾸기 -> 헤더 컨트롤바 수정
- 메뉴 등록에서 메뉴없으면 메뉴가 없습니다 -> 출력되도록 수정
- 메뉴등록 완료버튼있어야 할 것 같다 -> 모달창으로 수정
- 비건레벨 가게생성페이지에서 선택 안됨 -> 선택되도록 수정
- 로그인 되어있을 때 로그인 버튼이 잠깐 보이는 버그 픽스 -> 임의로 timeout 설정
> 버그 수정사항 반영
